spring:
  jpa:
    show-sql: false 
    generate-ddl: true
    hibernate:      
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        type: trace        
  datasource:
    driverClassName: org.postgresql.Driver
    connectionTimeout: 20000
    maxPoolSize: 10
    maxActive: 10
    maxIdle: 10
    initialSize: 5
    idleTimeout: 300000
    minIdle: 10
    poolName: app-connection-pool
    removeAbandoned: true
datasource:
  datalinks:
    01: DATABASE_URL
    02: HEROKU_POSTGRESQL_AMBER_URL
    03: HEROKU_POSTGRESQL_AQUA_URL
    04: HEROKU_POSTGRESQL_BLACK_URL
    05: HEROKU_POSTGRESQL_BLUE_URL
    06: HEROKU_POSTGRESQL_BRONZE_URL
    07: HEROKU_POSTGRESQL_BROWN_URL
    08: HEROKU_POSTGRESQL_CHARCOAL_URL
    09: HEROKU_POSTGRESQL_COBALT_URL
    10: HEROKU_POSTGRESQL_COPPER_URL
    11: HEROKU_POSTGRESQL_CRIMSON_URL
    12: HEROKU_POSTGRESQL_CYAN_URL
    13: HEROKU_POSTGRESQL_GOLD_URL
    14: HEROKU_POSTGRESQL_GRAY_URL
    15: HEROKU_POSTGRESQL_GREEN_URL
    16: HEROKU_POSTGRESQL_IVORY_URL
    17: HEROKU_POSTGRESQL_JADE_URL
    18: HEROKU_POSTGRESQL_MAROON_URL
    19: HEROKU_POSTGRESQL_MAUVE_URL
    20: HEROKU_POSTGRESQL_NAVY_URL
    21: HEROKU_POSTGRESQL_OLIVE_URL
    22: HEROKU_POSTGRESQL_ONYX_URL
    23: HEROKU_POSTGRESQL_ORANGE_URL
    24: HEROKU_POSTGRESQL_PINK_URL
    25: HEROKU_POSTGRESQL_PUCE_URL
    26: HEROKU_POSTGRESQL_PURPLE_URL
    27: HEROKU_POSTGRESQL_RED_URL
    28: HEROKU_POSTGRESQL_ROSE_URL
    29: HEROKU_POSTGRESQL_SILVER_URL
    30: HEROKU_POSTGRESQL_TEAL_URL
    31: HEROKU_POSTGRESQL_WHITE_URL
    32: HEROKU_POSTGRESQL_YELLOW_URL