spring:
  jpa:
    show-sql: false 
    generate-ddl: true
    hibernate: 
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        type: trace 
  datasource:
    driverClassName: org.postgresql.Driver
    connectionTimeout: 20000
    maxPoolSize: 10
    maxActive: 10
    maxIdle: 10
    initialSize: 5
    idleTimeout: 300000
    minIdle: 10
    poolName: app-connection-pool
    removeAbandoned: true