spring:
  jpa:
    show-sql: false 
    generate-ddl: true
    hibernate:      
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        type: trace        
  datasource:
    driverClassName: org.postgresql.Driver
    connectionTimeout: 20000
    maxPoolSize: 10
    maxActive: 10
    maxIdle: 10
    initialSize: 5
    idleTimeout: 300000
    minIdle: 10
    poolName: app-connection-pool
    removeAbandoned: true
datasource:
  datalinks:
    9999988: DATABASE_URL
    9999989: HEROKU_POSTGRESQL_AMBER_URL
    9999970: HEROKU_POSTGRESQL_AQUA_URL
    9999971: HEROKU_POSTGRESQL_BLACK_URL
    9999972: HEROKU_POSTGRESQL_BLUE_URL
    9999973: HEROKU_POSTGRESQL_BRONZE_URL
    9999974: HEROKU_POSTGRESQL_BROWN_URL
    9999975: HEROKU_POSTGRESQL_CHARCOAL_URL
    9999976: HEROKU_POSTGRESQL_COBALT_URL
    9999977: HEROKU_POSTGRESQL_COPPER_URL
    9999978: HEROKU_POSTGRESQL_CRIMSON_URL
    9999979: HEROKU_POSTGRESQL_CYAN_URL
    9999980: HEROKU_POSTGRESQL_GOLD_URL
    9999981: HEROKU_POSTGRESQL_GRAY_URL
    9999982: HEROKU_POSTGRESQL_GREEN_URL
    9999983: HEROKU_POSTGRESQL_IVORY_URL
    9999984: HEROKU_POSTGRESQL_JADE_URL
    9999985: HEROKU_POSTGRESQL_MAROON_URL
    9999986: HEROKU_POSTGRESQL_MAUVE_URL
    9999987: HEROKU_POSTGRESQL_NAVY_URL
    9999988: HEROKU_POSTGRESQL_OLIVE_URL
    9999989: HEROKU_POSTGRESQL_ONYX_URL
    9999990: HEROKU_POSTGRESQL_ORANGE_URL
    9999991: HEROKU_POSTGRESQL_PINK_URL
    9999992: HEROKU_POSTGRESQL_PUCE_URL
    9999993: HEROKU_POSTGRESQL_PURPLE_URL
    9999994: HEROKU_POSTGRESQL_RED_URL
    9999995: HEROKU_POSTGRESQL_ROSE_URL
    9999996: HEROKU_POSTGRESQL_SILVER_URL
    9999997: HEROKU_POSTGRESQL_TEAL_URL
    9999998: HEROKU_POSTGRESQL_WHITE_URL
    9999999: HEROKU_POSTGRESQL_YELLOW_URL